CREATE TABLE Users(
	id INTEGER PRIMARY KEY,
	Username CHAR(50) NOT NULL,
	Password CHAR(256) NOT NULL,
	Balance	REAL NOT NULL
);

CREATE TABLE Projects(
	id INTEGER PRIMARY KEY,
	Name CHAR(100) NOT NULL,
	Deadline CHAR(30) NOT NULL,
	Objective REAL NOT NULL,
	Description TEXT NOT NULL,
	OwnerUserId INTEGER NOT NULL,
	FOREIGN KEY(OwnerUserId) REFERENCES Users(id)
);

CREATE TABLE Administrators(
	id INTEGER PRIMARY KEY,
	ProjectId INTEGER NOT NULL,
	UserId INTEGER NOT NULL,
	FOREIGN KEY(UserId) REFERENCES Users(id),
	FOREIGN KEY(ProjectId) REFERENCES Projects(id)
);

CREATE TABLE Rewards(
	id INTEGER PRIMARY KEY,
	MinValue REAL NOT NULL,
	Name CHAR(100) NOT NULL,
	Description TEXT NOT NULL,
	ProjectId INTEGER NOT NULL,
	FOREIGN KEY(ProjectId) REFERENCES Projects(id)
);

CREATE TABLE Rewards_Users(
	id INTEGER PRIMARY KEY,
	RewardId INTEGER NOT NULL,
	WinnerUserId INTEGER NOT NULL,
	OwnerUserId	INTEGER	NOT NULL,	
	FOREIGN KEY(OwnerUserId) REFERENCES Users(id),
	FOREIGN KEY(WinnerUserId) REFERENCES Users(id),
	FOREIGN KEY(RewardId) REFERENCES Rewards(id)
);

CREATE TABLE Extras(
	id INTEGER PRIMARY KEY,
	MinValue REAL NOT NULL,
	Name CHAR(100) NOT NULL,
	Description TEXT NOT NULL,
	ProjectId INTEGER NOT NULL,
	FOREIGN KEY(ProjectId) REFERENCES Projects(id)
);

CREATE TABLE Extras_Users(
	id INTEGER PRIMARY KEY,
	RewardId INTEGER NOT NULL,
	WinnerUserId INTEGER NOT NULL,
	OwnerUserId	INTEGER NOT NULL,	
	FOREIGN KEY(OwnerUserId) REFERENCES Users(id),
	FOREIGN KEY(WinnerUserId) REFERENCES Users(id),
	FOREIGN KEY(RewardId) REFERENCES Rewards(id)
);

CREATE TABLE Transactions(
	id INTEGER PRIMARY KEY,
	UserId INTEGER NOT NULL,
	PathId INTEGER NOT NULL,
	Value REAL NOT NULL,
	FOREIGN KEY(UserId) REFERENCES Users(id),
	FOREIGN KEY(PathId) REFERENCES Paths(id)
);

CREATE TABLE Messages(
	id INTEGER PRIMARY KEY,
	ProjectId INTEGER NOT NULL,
	Subject	CHAR(100) NOT NULL,
	Question TEXT NOT NULL,
	Response TEXT,
	FromUserId INTEGER NOT NULL,
	ToUserId INTEGER NOT NULL,
	FOREIGN KEY(FromUserId) REFERENCES Users(id),
	FOREIGN KEY(ToUserId) REFERENCES Users(id),
	FOREIGN KEY(ProjectId) REFERENCES Projects(id)
);

CREATE TABLE Paths(
	id INTEGER PRIMARY KEY,
	Name CHAR(50) NOT NULL,
	ProjectId INTEGER NOT NULL,
	Description	TEXT NOT NULL,
	FOREIGN KEY(ProjectId) REFERENCES Projects(id)
);

CREATE TABLE Votes(
	id INTEGER PRIMARY KEY,
	UserId INTEGER NOT NULL,
	PathId INTEGER NOT NULL,
	FOREIGN KEY(PathId) REFERENCES Paths(id)
);